version: '3'

services:
  web:
    build: .
    command: bash -c "cd frontend/ && npm run build && cd ../backend/ && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: music_service
    volumes:
    - .:/code
    ports:
    - "8000:8000"