version: '3'

services:
  web:
    build: .
    command: bash -c "cd backend/ && python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: painted_skies
    volumes:
    - .:/code
    ports:
    - "8000:8000"