# Generated by Django 2.1.7 on 2019-03-21 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindmapper', '0003_auto_20190319_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'клас', 'verbose_name_plural': 'класи'},
        ),
        migrations.AlterModelOptions(
            name='mindmap',
            options={'verbose_name': 'ментальна карта', 'verbose_name_plural': 'ментальні карти'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='учні'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='вчитель'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='created_at',
            field=models.DateTimeField(verbose_name='створено о'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='edited_at',
            field=models.DateTimeField(verbose_name='змінено о'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='mindmap',
            field=models.TextField(verbose_name='ментальна карта'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to=settings.AUTH_USER_MODEL, verbose_name='власник'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='спільне користування'),
        ),
        migrations.AlterField(
            model_name='mindmap',
            name='title',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
    ]
